name: Node CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - name: Bazel Cache
        uses: actions/cache@v2.0.0
        with:
          path: |
            ~/.cache/bazel
          key: ${{ runner.os }}-bazel-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-bazel-
      - name: node_modules Cache
        uses: actions/cache@v2.0.0
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('yarn.lock') }}-${{ hashFiles('patches/*.patch') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-
      - uses: actions/checkout@v2.3.1
        with:
          submodules: true
          fetch-depth: 110
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn install
        run: |
          yarn install --frozen-lockfile
        env:
          CI: true
      - name: yarn build
        run: |
          yarn build --remote_upload_local_results=true
        env:
          CI: true
      - name: yarn test
        run: |
          yarn test --remote_upload_local_results=true
        env:
          CI: true
