name: Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - name: Bazel Cache
        uses: actions/cache@v2.0.0
        with:
          path: |
            ~/.cache/bazel
            ~/.cache/bazel-disk-cache
          key: ${{ runner.os }}-bazel-karma-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-bazel-karma-
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - uses: actions/checkout@v2.3.1
        with:
          submodules: true
          fetch-depth: 110
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn install
        run: |
          yarn install --frozen-lockfile
        env:
          CI: true
      - name: yarn build
        run: |
          yarn build
        env:
          CI: true
      - name: yarn test
        run: |
          yarn test
        env:
          CI: true
      - uses: saucelabs/sauce-connect-action@v1.0.0
        if: ${{ matrix.node-version == '12.x' }}
        with:
          username: ${{ secrets.SAUCE_USERNAME }}
          accessKey: ${{ secrets.SAUCE_ACCESS_KEY }}
          tunnelIdentifier: github-action-tunnel
      - name: Karma
        if: ${{ matrix.node-version == '12.x' }}
        run: yarn karma:ci --remote_upload_local_results=true --action_env=SAUCE_ACCESS_KEY --action_env=SAUCE_USERNAME
        env:
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
