name: Browser CI Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: SauceLabs Tests
    steps:
      - uses: actions/checkout@v2.3.1
      - name: Decrypt bazel GCS secret
        run: ./.github/scripts/decrypt_secret.sh
        env:
          SECRET_BAZEL_CACHE_JSON_PASSPHRASE: ${{ secrets.SECRET_BAZEL_CACHE_JSON_PASSPHRASE }}
      - name: Use Node.js 14
        uses: actions/setup-node@v2.1.0
        with:
          node-version: 14
      - name: yarn install
        run: yarn install --frozen-lockfile
        env:
          CI: true
      - uses: saucelabs/sauce-connect-action@v1.0.0
        with:
          username: ${{ secrets.SAUCE_USERNAME }}
          accessKey: ${{ secrets.SAUCE_ACCESS_KEY }}
          tunnelIdentifier: github-action-tunnel
      - name: Karma
        run: yarn karma:ci --define=SAUCE_USERNAME=${{ secrets.SAUCE_USERNAME }} --define=SAUCE_ACCESS_KEY=${{ secrets.SAUCE_ACCESS_KEY }}
