name: Browser CI Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: SauceLabs Tests
    steps:
      - name: Bazel Cache
        uses: actions/cache@v2.0.0
        with:
          path: |
            ~/.cache/bazel
          key: ${{ runner.os }}-bazel-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-bazel-
      - name: node_modules Cache
        uses: actions/cache@v2.0.0
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('yarn.lock') }}-${{ hashFiles('patches/*.patch') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-
      - uses: actions/checkout@v2.3.1
      - name: Use Node.js 14
        uses: actions/setup-node@v2.1.0
        with:
          node-version: 14
      - name: yarn install
        run: yarn install --frozen-lockfile
        env:
          CI: true
      - uses: saucelabs/sauce-connect-action@v1.0.0
        with:
          username: ${{ secrets.SAUCE_USERNAME }}
          accessKey: ${{ secrets.SAUCE_ACCESS_KEY }}
          tunnelIdentifier: github-action-tunnel
      - name: Karma
        run: yarn karma:ci --remote_upload_local_results=true --action_env=SAUCE_ACCESS_KEY --action_env=SAUCE_USERNAME
        env:
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
