name: Sauce Labs Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
        with:
          submodules: true
          fetch-depth: 110
      - uses: saucelabs/sauce-connect-action@v1.1.2
        with:
          username: ${{ secrets.SAUCE_USERNAME }}
          accessKey: ${{ secrets.SAUCE_ACCESS_KEY }}
          tunnelIdentifier: github-action-tunnel
      - name: Create certs
        run: |
          echo "${{ secrets.BUILDBUDDY_ORG_CERT }}">buildbuddy-cert.pem
          echo "${{ secrets.BUILDBUDDY_ORG_KEY }}">buildbuddy-key.pem
      - name: Karma
        run: bazel test --config=ci :karma-ci --action_env=SAUCE_ACCESS_KEY --action_env=SAUCE_USERNAME
        env:
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
