name: Unit Tests

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2.3.4
        with:
          submodules: true
          fetch-depth: 110
      - name: Create certs
        run: |
          echo "${{ secrets.BUILDBUDDY_ORG_CERT }}">buildbuddy-cert.pem
          echo "${{ secrets.BUILDBUDDY_ORG_KEY }}">buildbuddy-key.pem
      - name: build
        run: |
          bazel build //... --config=ci --build_metadata=COMMIT_SHA=$(git rev-parse HEAD)
        env:
          CI: true
      - name: test
        run: |
          bazel test //... --config=ci --build_metadata=COMMIT_SHA=$(git rev-parse HEAD)
        env:
          CI: true
